version: 1.2
workflows:
- name: HMMIBD
  subclass: wdl
  primaryDescriptorPath: /hmmIBD.wdl
- name: HMMIBD_OUTPUTS_VISUALIZATION
  subclass: wdl
  primaryDescriptorPath: /hmmIBD_Outputs_Visualization.wdl
- name: HMMIBD_CLEAN_VCF
  subclass: wdl
  primaryDescriptorPath: /hmmIBD_CleanVCF.wdl
- name: HMMIBD_CHOSE_MONOGENOMIC
  subclass: wdl
  primaryDescriptorPath: /hmmIBD_Chose_monogenomic.wdl